### ISSUE TITLE
Putting on ELPA

### ISSUE THREAD

**Issue by danlamanna** [papaeye/emacs-jscs#1]
Is there a way this package (with dependencies) can be put on one of emacs' online package repositories for easier installation? elpa, or melpa, etc?

Thanks for the package!

**Comment by avendael** [comment]
:+1: would be cool if this is on melpa!

**Comment by papaeye** [comment]
Sorry, I missed this issue.
I will do this in this weekend.

**Comment by walter** [comment]
:+1:

Looking forward to using this. Thanks for you work @papaeye.

**Comment by papaeye** [comment]
Merged!  Sorry for taking long to finish this.

**Comment by walter** [comment]
Got it! Thx!
