### ISSUE TITLE
M-x jscs-fix "Wrong number of arguments"

### ISSUE THREAD

**Issue by nathanlippi** [papaeye/emacs-jscs#2]
I'm getting the following error:
`let*: Wrong number of arguments: (lambda (file-name) (car (cdr (split-string file-name "\\.")))), 2`

I'm currently working on hunting it down, with limited elisp debugging skills.

Any help is appreciated.

**Comment by papaeye** [comment]
Could you paste the whole error message here?:
1. Eval `(setq debug-on-error t)` in the `*scratch*` buffer
2. Reproduce the error
3. Open `*Backtrace*` buffer
4. Paste the buffer content here

And what emacs version?:
1. Eval `emacs-version` in the `*scratch*` buffer

**Comment by nathanlippi** [comment]
Thanks much for getting back!

### Here's the backtrace I'm getting:

`Debugger entered--Lisp error: (wrong-number-of-arguments (lambda (file-name) (car (cdr (split-string file-name "\\.")))) 2)
  file-name-extension("/path/to/file.jsx" t)
  (let* ((tmpfile-suffix (file-name-extension (buffer-file-name) t)) (tmpfile (make-temp-file "jscs-fix" nil tmpfile-suffix)) (patchbuf (get-buffer-create "*Jscs-Fix patch*")) (errbuf (if jscs-fix-show-errors (get-buffer-create "*Jscs-Fix Errors*"))) (coding-system-for-read (quote utf-8)) (coding-system-for-write (quote utf-8))) (save-restriction (widen) (if errbuf (save-current-buffer (set-buffer errbuf) (setq buffer-read-only nil) (erase-buffer))) (save-current-buffer (set-buffer patchbuf) (erase-buffer)) (write-region nil nil tmpfile) (funcall (function jscs-fix--runner) tmpfile patchbuf errbuf) (kill-buffer patchbuf) (delete-file tmpfile)))
  jscs-fix()
  call-interactively(jscs-fix)
  (lambda nil (interactive) (call-interactively (intern (ido-completing-read "M-x " (all-completions "" obarray (quote commandp))))))()
  call-interactively((lambda nil (interactive) (call-interactively (intern (ido-completing-read "M-x " (all-completions "" obarray (quote commandp)))))) nil nil)
  command-execute((lambda nil (interactive) (call-interactively (intern (ido-completing-read "M-x " (all-completions "" obarray (quote commandp)))))))`

### And here's the output of `(emacs-version)`:

`"GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8)
 of 2015-09-07 on my-computer"`

**Comment by papaeye** [comment]
I suppose the definition of `file-name-extension` is customized somewhere (in your .emacs or some elisp package).
In Emacs 24.5, `file-name-extension` is defined in built-in files.el and has the following signature:

``` el
(file-name-extension FILENAME &optional PERIOD)
```

**Comment by nathanlippi** [comment]
@papaeye: Many thanks!  You're right.  I was able to hunt down the definition and fix it. (it was a defun I had written long ago)

Much appreciated.

**Comment by papaeye** [comment]
You're welcome! Closing.
