### ISSUE TITLE
M-x jscs-fix error

### ISSUE THREAD

**Issue by wkevina** [papaeye/emacs-jscs#3]
Hello, I'm having trouble with your package. I installed the most recent version on melpa, and when I run `M-x jscs-fix`, I get the following error:

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  #[0 "\301\302\303\304!!\"\207" [jscs-command expand-file-name "../lib/node_modules/" file-name-directory executable-find] 5 "\n\n(fn)"]()
  funcall(#[0 "\301\302\303\304!!\"\207" [jscs-command expand-file-name "../lib/node_modules/" file-name-directory executable-find] 5 "\n\n(fn)"])
  eval((funcall (function #[0 "\301\302\303\304!!\"\207" [jscs-command expand-file-name "../lib/node_modules/" file-name-directory executable-find] 5 "\n\n(fn)"])))
  byte-code("\303\304N\211\203  @\202\n)!\207" [symbol sv exp eval saved-value] 4)
  custom-initialize-reset(jscs-node-path (funcall (function #[0 "\301\302\303\304!!\"\207" [jscs-command expand-file-name "../lib/node_modules/" file-name-directory executable-find] 5 "\n\n(fn)"])))
  custom-declare-variable(jscs-node-path (funcall (function #[0 "\301\302\303\304!!\"\207" [jscs-command expand-file-name "../lib/node_modules/" file-name-directory executable-find] 5 "\n\n(fn)"])) "The NODE_PATH environment variable." :type string :group jscs)
  byte-code("\300\301\302\303\304\305%\210\306\307\310\311\312DD\313\314\315\304\301&\210\306\316\310\311\317DD\320\314\315\304\301&\210\306\321\310\311\322DD\323\314\315\304\301&\207" [custom-declare-group jscs nil "Consistent JavaScript editing using JSCS" :group tools custom-declare-variable jscs-command funcall function #[0 "\300\207" ["jscs"] 1 "jscs\n\n(fn)"] "The 'jscs' command." :type string jscs-node-command #[0 "\300\207" ["node"] 1 "node\n\n(fn)"] "The 'node' command." jscs-node-path #[0 "\301\302\303\304!!\"\207" [jscs-command expand-file-name "../lib/node_modules/" file-name-directory executable-find] 5 "\n\n(fn)"] "The NODE_PATH environment variable."] 8)
  autoload-do-load((autoload "jscs" nil t nil) jscs-fix)
  command-execute(jscs-fix record)
  execute-extended-command(nil "jscs-fix")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

I have jscs set up properly, with a .jscsrc in the current directory, if that helps.

**Comment by wkevina** [comment]
I was able to solve this issue; it looks like my node was installed in `/usr/local/bin`, which was not in my emacs' `exec-path`. Fixing that prevents the previous error. However, it's still not working for me. Instead, I get:

```
jscs-fix errors:
env: node: No such file or directory
```

When run on a plain javascript file.

**Comment by wkevina** [comment]
Nevermind, just a bunch of path non-sense. Installing package `exec-path-from-shell` solved all my issues.

**Comment by papaeye** [comment]
Thanks for reporting.  Updated the documentation.
